<?xml version="1.0" encoding="utf-8"?>
<RunHistoryData objectID="0">
  <ZipCounter>1</ZipCounter>
  <UserActions objectID="1">
    <Elements isCollection="True">
      <UserActionHistoryEntry objectID="2" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="3" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_1.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="4">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="5">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="6" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="7">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:24:30</Time>
        <Description>Tap navigationBarBackground view.</Description>
        <Comment isNull="True" />
        <UserActionIndex>1</UserActionIndex>
        <RelevantStepIndex>1</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="8" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="9" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_2.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="10">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="11">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="12" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="13">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:24:40</Time>
        <Description>Tap Find a Facility label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>2</UserActionIndex>
        <RelevantStepIndex>2</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="14" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="15" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_3.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="16">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="17">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="18" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="19">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:24:44</Time>
        <Description>Tap Allow button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>3</UserActionIndex>
        <RelevantStepIndex>2</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="20" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="21" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_4.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="22">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="23">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="24" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="25">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:05</Time>
        <Description>Tap Close button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>4</UserActionIndex>
        <RelevantStepIndex>4</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="26" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="27" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_5.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="28">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="29">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="30" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="31">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:22</Time>
        <Description>Tap SearchIcon label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>5</UserActionIndex>
        <RelevantStepIndex>5</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="32" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="33" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_6.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="34">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="35">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="36" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="37">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:32</Time>
        <Description>Set focus to search_address_edit_text input field.</Description>
        <Comment isNull="True" />
        <UserActionIndex>6</UserActionIndex>
        <RelevantStepIndex>6</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="38" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="39" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_7.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="40">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="41">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="42" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="43">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:40</Time>
        <Description>Enter 94566.</Description>
        <Comment isNull="True" />
        <UserActionIndex>7</UserActionIndex>
        <RelevantStepIndex>6</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="44" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="45" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_8.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="46">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="47">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="48" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="49">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:40</Time>
        <Description>Tap Google Map view.</Description>
        <Comment isNull="True" />
        <UserActionIndex>8</UserActionIndex>
        <RelevantStepIndex>6</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="50" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="51" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_9.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="52">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="53">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="54" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="55">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:25:58</Time>
        <Description>Tap Filter label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>9</UserActionIndex>
        <RelevantStepIndex>7</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="56" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="57" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_10.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="58">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="59">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="60" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="61">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:26:14</Time>
        <Description>Tap Emergency Services checked label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>10</UserActionIndex>
        <RelevantStepIndex>8</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="62" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="63" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_11.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="64">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="65">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="66" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="67">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:26:16</Time>
        <Description>Tap OK button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>11</UserActionIndex>
        <RelevantStepIndex>8</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="68" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="69" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_12.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="70">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="71">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="72" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="73">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:26:25</Time>
        <Description>Set state of locator_list_button toggle button to on.</Description>
        <Comment isNull="True" />
        <UserActionIndex>12</UserActionIndex>
        <RelevantStepIndex>9</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="74" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="75" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_13.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="76">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="77">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="78" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="79">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:27:26</Time>
        <Description>Tap Kaiser Permanente Fremont Medical Center and Offices label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>13</UserActionIndex>
        <RelevantStepIndex>10</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="80" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="81" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_14.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="82">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="83">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="84" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="85">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:28:30</Time>
        <Description>Tap Deny button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>14</UserActionIndex>
        <RelevantStepIndex>10</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="86" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="87" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_15.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="88">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="89">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="90" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="91">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:28:32</Time>
        <Description>Tap Kaiser Permanente Fremont Medical Center and Offices label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>15</UserActionIndex>
        <RelevantStepIndex>10</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="92" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="93" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_16.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="94">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="95">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="96" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="97">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-18T16:28:34</Time>
        <Description>Tap Deny button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>16</UserActionIndex>
        <RelevantStepIndex>10</RelevantStepIndex>
      </UserActionHistoryEntry>
    </Elements>
  </UserActions>
  <RunDefinition objectID="98">
    <ContainedAut objectID="99">
      <IsDefault>True</IsDefault>
      <ID>f5359cbf-a715-4eaa-aaff-abadfe776604</ID>
      <Name>New Application</Name>
      <Description isNull="True" />
      <AddinsDefinition objectID="100">
        <Elements isCollection="True" />
      </AddinsDefinition>
      <ExecutionType>Web</ExecutionType>
      <StationsAutDefinition objectID="101">
        <RecorderAutDefinition objectID="102">
          <ExecutionDefinition objectID="103" type="HP.MirrorTesting.Common.WebExecutionDefinition, HP.Sprinter.Common">
            <URL></URL>
            <Browser>IEXPLORE</Browser>
            <WebReplayType>Event</WebReplayType>
          </ExecutionDefinition>
          <RunMode>CreateNew</RunMode>
          <CloseAutAtRunEnd>False</CloseAutAtRunEnd>
        </RecorderAutDefinition>
        <Elements isCollection="True">
          <StationAutDefinition cyclicReferenceObjectID="102" />
        </Elements>
      </StationsAutDefinition>
    </ContainedAut>
    <ID objectID="104">
      <ID>4</ID>
      <TestInstanceID>0</TestInstanceID>
    </ID>
    <InRunQueue>True</InRunQueue>
    <RunSettings objectID="105">
      <Name>4</Name>
      <IsDraftRun>False</IsDraftRun>
      <ExecutionStartTime>2017-07-18T16:23:51</ExecutionStartTime>
      <ExecutionEndTime>2017-07-18T16:28:43</ExecutionEndTime>
      <IsSprinterRun>True</IsSprinterRun>
      <ExecutionDuration>00:04:51.7337699</ExecutionDuration>
      <Status>Not Completed</Status>
      <Tester>HPE</Tester>
      <Comments isNull="True" />
      <IsLockedBySomeoneElse>False</IsLockedBySomeoneElse>
      <IsLockedDueToBusinessRules type="System.Boolean, mscorlib">False</IsLockedDueToBusinessRules>
      <IsViewerPermissions>False</IsViewerPermissions>
      <IsPowerTestingOn type="System.Boolean, mscorlib">False</IsPowerTestingOn>
      <RunID>4</RunID>
    </RunSettings>
    <TestID objectID="106">
      <IntID>0</IntID>
    </TestID>
    <StationsDefinition objectID="107">
      <Collection objectID="108">
        <Elements isCollection="True">
          <StationDefinition objectID="109">
            <MachineDefinition objectID="110">
              <CredentialsInfo objectID="111">
                <Source>CurrUser</Source>
              </CredentialsInfo>
              <Location objectID="112" type="HP.MirrorTesting.BL.Data.TestDefinitionData.RunDefinition.Host.LocationDefinition, HP.Sprinter.BL.Data">
                <HostNameOrAddress>localhost</HostNameOrAddress>
                <HostName>localhost</HostName>
                <Address isNull="True" />
              </Location>
              <Credentials objectID="113" type="HP.MirrorTesting.BL.Data.TestDefinitionData.RunDefinition.Host.CredentialsDefinition, HP.Sprinter.BL.Data">
                <EncryptedPassword isNull="True" />
                <Username isNull="True" />
                <FullUsername isNull="True" />
                <UserDomain isNull="True" />
              </Credentials>
            </MachineDefinition>
            <AgentDefinition objectID="114">
              <Name>Primary</Name>
              <Description>Primary Machine</Description>
              <ImageSource>Host</ImageSource>
              <Protocol>Pipe</Protocol>
              <StationType>Recorder</StationType>
            </AgentDefinition>
            <StationAutDefinitionPointer objectID="115">
              <PointedID>0</PointedID>
              <PointerType>StationAut</PointerType>
            </StationAutDefinitionPointer>
            <IsExcluded>False</IsExcluded>
            <LastModificationTime isNull="True" />
          </StationDefinition>
        </Elements>
      </Collection>
    </StationsDefinition>
    <AutDefinition cyclicReferenceObjectID="99" />
    <StepsDefinition objectID="116">
      <Elements isCollection="True">
        <StepDefinition objectID="117">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>1</StepIndex>
          <Name>Step 1</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap navigationBarBackground view.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:24:32</ExecutionTime>
          <DesignTimeAttachments objectID="118">
            <Elements isCollection="True" />
          </DesignTimeAttachments>
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;close keyboard&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="119">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap navigationBarBackground view.</TextualDescription>
          <TextualExpectedResults>close keyboard</TextualExpectedResults>
          <LocalStepDirectory>khic1snz.kxx</LocalStepDirectory>
          <Context objectID="120">
            <Elements isCollection="True">
              <StepContext objectID="121">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="122">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="123">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>2</StepIndex>
          <Name>Step 2</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Find a Facility label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:24:46</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show 'allow access to location' alert&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="124">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Find a Facility label.</TextualDescription>
          <TextualExpectedResults>show 'allow access to location' alert</TextualExpectedResults>
          <LocalStepDirectory>fd1aszm3.vvc</LocalStepDirectory>
          <Context objectID="125">
            <Elements isCollection="True">
              <StepContext objectID="126">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="127">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="128">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>3</StepIndex>
          <Name>Step 3</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Allow button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:24:48</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show 'important:...' alert&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="129">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Allow button.</TextualDescription>
          <TextualExpectedResults>show 'important:...' alert</TextualExpectedResults>
          <LocalStepDirectory>014ml4cq.3yw</LocalStepDirectory>
          <Context objectID="130">
            <Elements isCollection="True">
              <StepContext objectID="131">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="132">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="133">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>4</StepIndex>
          <Name>Step 4</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Close button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:25:18</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Find a facility screen to show&lt;/span&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="134">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Close button.</TextualDescription>
          <TextualExpectedResults>Find a facility screen to show</TextualExpectedResults>
          <LocalStepDirectory>jqcguttx.3l5</LocalStepDirectory>
          <Context objectID="135">
            <Elements isCollection="True">
              <StepContext objectID="136">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="137">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="138">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>5</StepIndex>
          <Name>Step 5</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap SearchIcon label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:25:27</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search field become editable&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="139">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap SearchIcon label.</TextualDescription>
          <TextualExpectedResults>search field become editable</TextualExpectedResults>
          <LocalStepDirectory>qqhc4z3s.bhp</LocalStepDirectory>
          <Context objectID="140">
            <Elements isCollection="True">
              <StepContext objectID="141">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="142">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="143">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>6</StepIndex>
          <Name>Step 6</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Enter 94566.&lt;/span&gt;&lt;br /&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Google Map view.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:25:49</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search execute and result show on map&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="144">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Enter 94566.
Tap Google Map view.</TextualDescription>
          <TextualExpectedResults>search execute and result show on map</TextualExpectedResults>
          <LocalStepDirectory>t2140cfy.tvj</LocalStepDirectory>
          <Context objectID="145">
            <Elements isCollection="True">
              <StepContext objectID="146">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="147">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="148">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>7</StepIndex>
          <Name>Step 7</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Filter label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:26:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;open filter view&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="149">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Filter label.</TextualDescription>
          <TextualExpectedResults>open filter view</TextualExpectedResults>
          <LocalStepDirectory>teccm2of.3b1</LocalStepDirectory>
          <Context objectID="150">
            <Elements isCollection="True">
              <StepContext objectID="151">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="152">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="153">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>8</StepIndex>
          <Name>Step 8</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Emergency Cervices checked label.&lt;/span&gt;&lt;br /&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap OK button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:26:21</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search results should be filtered &lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="154">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Emergency Cervices checked label.
Tap OK button.</TextualDescription>
          <TextualExpectedResults>search results should be filtered</TextualExpectedResults>
          <LocalStepDirectory>sfgjkhe3.lfv</LocalStepDirectory>
          <Context objectID="155">
            <Elements isCollection="True">
              <StepContext objectID="156">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="157">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="158">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>9</StepIndex>
          <Name>Step 9</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap LIST&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-18T16:27:20</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show 'allow access to contact&amp;quot; alert&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="159">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap LIST</TextualDescription>
          <TextualExpectedResults>show 'allow access to contact" alert</TextualExpectedResults>
          <LocalStepDirectory>ts44cmno.scb</LocalStepDirectory>
          <Context objectID="160">
            <Elements isCollection="True">
              <StepContext objectID="161">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="162">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="163">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>10</StepIndex>
          <Name>Step 10</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Set state of locator_list_button toggle button to on.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;list view mode should display list of facilities&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="164">
            <SnapshotPartialPath>C:\Users\HPE\Documents\KP - July 2017\KP-Find-Facility-Test_Data\Resources\Steps\2wy1ycn3.zqd\ScreenCapture_-2017-07-18_15-55-25-643.jpg</SnapshotPartialPath>
          </SnapshotDefinition>
          <IsCurrent>True</IsCurrent>
          <TextualDescription>Set state of locator_list_button toggle button to on.</TextualDescription>
          <TextualExpectedResults>list view mode should display list of facilities</TextualExpectedResults>
          <LocalStepDirectory>2wy1ycn3.zqd</LocalStepDirectory>
          <Context objectID="165">
            <Elements isCollection="True">
              <StepContext objectID="166">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="167">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="168">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>3</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>11</StepIndex>
          <Name>Step 11</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Kaiser Permanente Fremont Medical Center and Offices label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="118" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show facility details&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="100" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="118" />
          <SnapshotDefinition objectID="169">
            <SnapshotPartialPath>C:\Users\HPE\Documents\KP - July 2017\KP-Find-Facility-Test_Data\Resources\Steps\nys0q3ps.0n5\ScreenCapture_-2017-07-18_15-55-06-535.jpg</SnapshotPartialPath>
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Kaiser Permanente Fremont Medical Center and Offices label.</TextualDescription>
          <TextualExpectedResults>show facility details</TextualExpectedResults>
          <LocalStepDirectory>nys0q3ps.0n5</LocalStepDirectory>
          <Context objectID="170">
            <Elements isCollection="True">
              <StepContext objectID="171">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="172">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="98" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
      </Elements>
    </StepsDefinition>
    <HierarchyRoot isNull="True" />
    <Parameters objectID="173">
      <Elements isCollection="True" />
    </Parameters>
    <Attachments cyclicReferenceObjectID="118" />
    <ComputedStatus>Not Completed</ComputedStatus>
  </RunDefinition>
  <Comments objectID="174">
    <Elements isCollection="True" />
  </Comments>
  <Bookmarks objectID="175">
    <Elements isCollection="True" />
  </Bookmarks>
  <ReportedBugs objectID="176">
    <Elements isCollection="True" />
  </ReportedBugs>
</RunHistoryData>