<?xml version="1.0" encoding="utf-8"?>
<RunHistoryData objectID="0">
  <ZipCounter>1</ZipCounter>
  <UserActions objectID="1">
    <Elements isCollection="True">
      <UserActionHistoryEntry objectID="2" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="3" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_1.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="4">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="5">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>False</ScreenshotUploaded>
        </Master>
        <Slaves objectID="6" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="7">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-24T20:07:46</Time>
        <Description>Click the device's Back button.</Description>
        <Comment isNull="True" />
        <UserActionIndex>1</UserActionIndex>
        <RelevantStepIndex>1</RelevantStepIndex>
      </UserActionHistoryEntry>
      <UserActionHistoryEntry objectID="8" type="HP.MirrorTesting.BL.Modules.RunHistory.UserActionHistoryEntry, HP.Sprinter.BL.Modules">
        <Master objectID="9" type="HP.MirrorTesting.BL.Modules.RunHistory.StationHistoryEntry, HP.Sprinter.BL.Modules">
          <Parent cyclicReferenceObjectID="0" />
          <ImageFileName>-1_2.jpg</ImageFileName>
          <Data isNull="True" />
          <StationID>-1</StationID>
          <StationStates objectID="10">
            <MirroringState>NotReady</MirroringState>
            <TechnicalState>Excluded</TechnicalState>
          </StationStates>
          <StepErrors objectID="11">
            <Elements isCollection="True" />
          </StepErrors>
          <ScreenshotUploaded>True</ScreenshotUploaded>
        </Master>
        <Slaves objectID="12" type="HP.MirrorTesting.BL.Modules.RunHistory.SlaveHistoryEntryCollection, HP.Sprinter.BL.Modules">
          <Map objectID="13">
            <Elements isCollection="True" />
          </Map>
        </Slaves>
        <Time>2017-07-24T20:07:54</Time>
        <Description>Tap Find a Facility label.</Description>
        <Comment isNull="True" />
        <UserActionIndex>2</UserActionIndex>
        <RelevantStepIndex>2</RelevantStepIndex>
      </UserActionHistoryEntry>
    </Elements>
  </UserActions>
  <RunDefinition objectID="14">
    <ContainedAut objectID="15">
      <IsDefault>False</IsDefault>
      <ID>107a5789-f153-497c-8a00-677f76683629</ID>
      <Name>Kaiser</Name>
      <Description isNull="True" />
      <AddinsDefinition objectID="16">
        <Elements isCollection="True">
          <String>Mobile</String>
        </Elements>
      </AddinsDefinition>
      <ExecutionType>Mobile</ExecutionType>
      <StationsAutDefinition objectID="17">
        <RecorderAutDefinition objectID="18">
          <ExecutionDefinition objectID="19" type="HP.MirrorTesting.Common.MobileExecutionDefinition, HP.Sprinter.Common">
            <IsSapUI5>False</IsSapUI5>
            <URL isNull="True" />
            <Job objectID="20">
              <name>6b000420-6bf0-4119-bea4-01c5cb7919d9</name>
              <id>e7d3209a-da5f-45fd-8285-e3ecaa02cfe6</id>
              <status>TEMP</status>
              <application objectID="21">
                <type>ANDROID</type>
                <id>8b6d3803-05c4-4b09-a436-2e16e7f9b312</id>
                <name>KP</name>
                <version>41500006</version>
                <counter>1</counter>
                <fileName>KP_org.kp.m.apk</fileName>
                <identifier>org.kp.m</identifier>
                <instrumented>False</instrumented>
              </application>
              <devices objectID="22">
                <Elements isCollection="True">
                  <Device objectID="23">
                    <deviceID>0a9e0bfe</deviceID>
                    <serialNumber>0a9e0bfe</serialNumber>
                    <logicName>Nexus 7</logicName>
                    <model>Nexus 7</model>
                    <osVersion>6.0.1</osVersion>
                    <osType>ANDROID</osType>
                    <deviceStatus>registered</deviceStatus>
                    <manufacturer>asus</manufacturer>
                  </Device>
                </Elements>
              </devices>
              <header>{"collect":{"cpu":false,"memory":false,"freeMemory":false,"logs":false,"screenshot":true},"configuration":{"installAppBeforeExecution":false,"deleteAppAfterExecution":false,"restartApp":true,"launchApplication":true,"wipeData":false,"injectedJsId":null,"maxStepTimeOut":300},"networkConditionsProfileId":null}</header>
              <capableDeviceFilterDetails isNull="True" />
              <extraApps isNull="True" />
            </Job>
            <NetworkProfiles isNull="True" />
          </ExecutionDefinition>
          <RunMode>CreateNew</RunMode>
          <CloseAutAtRunEnd>False</CloseAutAtRunEnd>
        </RecorderAutDefinition>
        <Elements isCollection="True">
          <StationAutDefinition cyclicReferenceObjectID="18" />
        </Elements>
      </StationsAutDefinition>
    </ContainedAut>
    <ID objectID="24">
      <ID>9</ID>
      <TestInstanceID>0</TestInstanceID>
    </ID>
    <InRunQueue>False</InRunQueue>
    <RunSettings objectID="25">
      <Name>9</Name>
      <IsDraftRun>False</IsDraftRun>
      <ExecutionStartTime>2017-07-24T20:07:21</ExecutionStartTime>
      <ExecutionEndTime>2017-07-24T20:14:41</ExecutionEndTime>
      <IsSprinterRun>True</IsSprinterRun>
      <ExecutionDuration>00:07:20.5412279</ExecutionDuration>
      <Status>Failed</Status>
      <Tester>HPE</Tester>
      <Comments isNull="True" />
      <IsLockedBySomeoneElse>False</IsLockedBySomeoneElse>
      <IsLockedDueToBusinessRules type="System.Boolean, mscorlib">False</IsLockedDueToBusinessRules>
      <IsViewerPermissions>False</IsViewerPermissions>
      <IsPowerTestingOn type="System.Boolean, mscorlib">False</IsPowerTestingOn>
      <RunID>9</RunID>
    </RunSettings>
    <TestID objectID="26">
      <IntID>0</IntID>
    </TestID>
    <StationsDefinition objectID="27">
      <Collection objectID="28">
        <Elements isCollection="True">
          <StationDefinition objectID="29">
            <MachineDefinition objectID="30">
              <CredentialsInfo objectID="31">
                <Source>CurrUser</Source>
              </CredentialsInfo>
              <Location objectID="32" type="HP.MirrorTesting.BL.Data.TestDefinitionData.RunDefinition.Host.LocationDefinition, HP.Sprinter.BL.Data">
                <HostNameOrAddress>localhost</HostNameOrAddress>
                <HostName>localhost</HostName>
                <Address isNull="True" />
              </Location>
              <Credentials objectID="33" type="HP.MirrorTesting.BL.Data.TestDefinitionData.RunDefinition.Host.CredentialsDefinition, HP.Sprinter.BL.Data">
                <EncryptedPassword isNull="True" />
                <Username isNull="True" />
                <FullUsername isNull="True" />
                <UserDomain isNull="True" />
              </Credentials>
            </MachineDefinition>
            <AgentDefinition objectID="34">
              <Name>Primary</Name>
              <Description>Primary Machine</Description>
              <ImageSource>Host</ImageSource>
              <Protocol>Pipe</Protocol>
              <StationType>Recorder</StationType>
            </AgentDefinition>
            <StationAutDefinitionPointer objectID="35">
              <PointedID>0</PointedID>
              <PointerType>StationAut</PointerType>
            </StationAutDefinitionPointer>
            <IsExcluded>False</IsExcluded>
            <LastModificationTime isNull="True" />
          </StationDefinition>
        </Elements>
      </Collection>
    </StationsDefinition>
    <AutDefinition cyclicReferenceObjectID="15" />
    <StepsDefinition objectID="36">
      <Elements isCollection="True">
        <StepDefinition objectID="37">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>1</StepIndex>
          <Name>Step 1</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap navigationBarBackground view.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Passed</Status>
          <ExecutionTime>2017-07-24T20:07:49</ExecutionTime>
          <DesignTimeAttachments objectID="38">
            <Elements isCollection="True" />
          </DesignTimeAttachments>
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;close keyboard&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments objectID="39">
            <Elements isCollection="True" />
          </RuntimeAttachments>
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="40">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap navigationBarBackground view.</TextualDescription>
          <TextualExpectedResults>close keyboard</TextualExpectedResults>
          <LocalStepDirectory>khic1snz.kxx</LocalStepDirectory>
          <Context objectID="41">
            <Elements isCollection="True">
              <StepContext objectID="42">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="43">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="44">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>2</StepIndex>
          <Name>Step 2</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Find a Facility label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>Failed</Status>
          <ExecutionTime>2017-07-24T20:07:59</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show 'allow access to location' alert&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="45">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>True</IsCurrent>
          <TextualDescription>Tap Find a Facility label.</TextualDescription>
          <TextualExpectedResults>show 'allow access to location' alert</TextualExpectedResults>
          <LocalStepDirectory>fd1aszm3.vvc</LocalStepDirectory>
          <Context objectID="46">
            <Elements isCollection="True">
              <StepContext objectID="47">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="48">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="49">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>3</StepIndex>
          <Name>Step 3</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Allow button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;show 'important:...' alert&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="50">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Allow button.</TextualDescription>
          <TextualExpectedResults>show 'important:...' alert</TextualExpectedResults>
          <LocalStepDirectory>014ml4cq.3yw</LocalStepDirectory>
          <Context objectID="51">
            <Elements isCollection="True">
              <StepContext objectID="52">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="53">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="54">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>4</StepIndex>
          <Name>Step 4</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Close button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Find a facility screen to show&lt;/span&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="55">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Close button.</TextualDescription>
          <TextualExpectedResults>Find a facility screen to show</TextualExpectedResults>
          <LocalStepDirectory>jqcguttx.3l5</LocalStepDirectory>
          <Context objectID="56">
            <Elements isCollection="True">
              <StepContext objectID="57">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="58">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="59">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>5</StepIndex>
          <Name>Step 5</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap SearchIcon label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search field become editable&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="60">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap SearchIcon label.</TextualDescription>
          <TextualExpectedResults>search field become editable</TextualExpectedResults>
          <LocalStepDirectory>qqhc4z3s.bhp</LocalStepDirectory>
          <Context objectID="61">
            <Elements isCollection="True">
              <StepContext objectID="62">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="63">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="64">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>6</StepIndex>
          <Name>Step 6</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Enter 94566.&lt;/span&gt;&lt;br /&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Google Map view.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search execute and result show on map&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="65">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Enter 94566.
Tap Google Map view.</TextualDescription>
          <TextualExpectedResults>search execute and result show on map</TextualExpectedResults>
          <LocalStepDirectory>t2140cfy.tvj</LocalStepDirectory>
          <Context objectID="66">
            <Elements isCollection="True">
              <StepContext objectID="67">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="68">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="69">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>7</StepIndex>
          <Name>Step 7</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Filter label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;open filter view&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="70">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Filter label.</TextualDescription>
          <TextualExpectedResults>open filter view</TextualExpectedResults>
          <LocalStepDirectory>teccm2of.3b1</LocalStepDirectory>
          <Context objectID="71">
            <Elements isCollection="True">
              <StepContext objectID="72">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="73">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="74">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>8</StepIndex>
          <Name>Step 8</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Emergency Services checked label.&lt;/span&gt;&lt;br /&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap OK button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;search results should be filtered &lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="75">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Emergency Services checked label.
Tap OK button.</TextualDescription>
          <TextualExpectedResults>search results should be filtered</TextualExpectedResults>
          <LocalStepDirectory>sfgjkhe3.lfv</LocalStepDirectory>
          <Context objectID="76">
            <Elements isCollection="True">
              <StepContext objectID="77">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="78">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="79">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>9</StepIndex>
          <Name>Step 9</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap LIST&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;disply facilities list&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="80">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap LIST</TextualDescription>
          <TextualExpectedResults>disply facilities list</TextualExpectedResults>
          <LocalStepDirectory>ts44cmno.scb</LocalStepDirectory>
          <Context objectID="81">
            <Elements isCollection="True">
              <StepContext objectID="82">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="83">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="84">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>10</StepIndex>
          <Name>Step 10</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Kaiser Permanente Fremont Medical Center and Offices label.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults isNull="True" />
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="85">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Kaiser Permanente Fremont Medical Center and Offices label.</TextualDescription>
          <TextualExpectedResults></TextualExpectedResults>
          <LocalStepDirectory>3jpowk0p.42d</LocalStepDirectory>
          <Context objectID="86">
            <Elements isCollection="True">
              <StepContext objectID="87">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="88">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
        <StepDefinition objectID="89">
          <Id>-1</Id>
          <RunStepId>0</RunStepId>
          <TestId>2</TestId>
          <SourceTestName isNull="True" />
          <StepIndex>11</StepIndex>
          <Name>Step 11</Name>
          <Description>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Tap Allow button.&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</Description>
          <Status>No Run</Status>
          <ExecutionTime>0001-01-01T00:00:00</ExecutionTime>
          <DesignTimeAttachments cyclicReferenceObjectID="38" />
          <ExpectedResults>&lt;html&gt;&lt;body&gt;&lt;span style="font-family: 'Arial';font-style: Normal;font-weight: normal;font-size: 8.00pt;"&gt;Display facility info&lt;/span&gt;&lt;/body&gt;&lt;/html&gt;</ExpectedResults>
          <TextualActualResults isNull="True" />
          <ActualResults isNull="True" />
          <ActualResultsImagePath isNull="True" />
          <RuntimeAttachments cyclicReferenceObjectID="39" />
          <RuntimeAttachmentDefinitions cyclicReferenceObjectID="38" />
          <SnapshotDefinition objectID="90">
            <SnapshotPartialPath isNull="True" />
          </SnapshotDefinition>
          <IsCurrent>False</IsCurrent>
          <TextualDescription>Tap Allow button.</TextualDescription>
          <TextualExpectedResults>Display facility info</TextualExpectedResults>
          <LocalStepDirectory>s2smfzd4.gvb</LocalStepDirectory>
          <Context objectID="91">
            <Elements isCollection="True">
              <StepContext objectID="92">
                <TestName>KP-Find-Facility-Test</TestName>
                <IsStepOwner>True</IsStepOwner>
              </StepContext>
            </Elements>
          </Context>
          <UserDefinedFieldValues objectID="93">
            <Elements isCollection="True" />
          </UserDefinedFieldValues>
          <BPTStepContainer isNull="True" />
          <ContainerRun cyclicReferenceObjectID="14" />
          <IsDirty>True</IsDirty>
        </StepDefinition>
      </Elements>
    </StepsDefinition>
    <HierarchyRoot isNull="True" />
    <Parameters objectID="94">
      <Elements isCollection="True" />
    </Parameters>
    <Attachments cyclicReferenceObjectID="38" />
    <ComputedStatus>Failed</ComputedStatus>
  </RunDefinition>
  <Comments objectID="95">
    <Elements isCollection="True" />
  </Comments>
  <Bookmarks objectID="96">
    <Elements isCollection="True" />
  </Bookmarks>
  <ReportedBugs objectID="97">
    <Elements isCollection="True" />
  </ReportedBugs>
</RunHistoryData>